const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    email: 'glavin617@gmail.com',
    first_name: 'KEVIN',
    middle_name: 'L',
    last_name: 'DELA PEÑA',
    suffix: '',
    password: '123456',
    role: 'student',
  },
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442b',
    email: 'user1@nextmail.com',
    first_name: 'REYJON',
    middle_name: 'P',
    last_name: 'RAMIREZ',
    suffix: '',
    password: '123456',
    role: 'student',
  },
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442c',
    email: 'user2@nextmail.com',
    first_name: 'Juniper',
    middle_name: 'P',
    last_name: 'Banaybanay',
    suffix: '',
    password: '123456',
    role: 'administrator',
  },
];

const students = [
  {
    id_number: '2021-0003829',
    gender: 'MALE',
    civil_status: 'MARRIED',
    birthday: 'SEPTEMBER 26, 1995',
    birth_place: 'SOCORRO, SURIGAO DEL NORTE',
    age: 27,
    nationality: 'FIL',
    religion: 'CHURCH OF JESUS CHRIST OF LATT',
    ethnicity: 'BISAYA',
    facebook: '',
    skype: '',
    zoom_account: '',
    course_id: '64ffa120-aa8a-4ab1-9396-4100342fb0f5',
    user_id: '410544b2-4001-4271-9855-fec4b6a6442a',
  },
  {
    id_number: '2021-0003830',
    gender: 'MALE',
    civil_status: 'SINGLE',
    birthday: 'SEPTEMBER 19, 2000',
    birth_place: 'SOCORRO, SURIGAO DEL NORTE',
    age: 23,
    nationality: 'FIL',
    religion: '',
    ethnicity: 'BISAYA',
    facebook: '',
    skype: '',
    zoom_account: '',
    course_id: '17c19242-7bcf-455c-b771-6b2c50371245',
    user_id: '410544b2-4001-4271-9855-fec4b6a6442b',
  }
]

const courses = [
  {
    id: '64ffa120-aa8a-4ab1-9396-4100342fb0f5',
    industry_sector: 'Metals and Engineering',
    program_title: 'Shielded Metal Arc Wielding',
  },
  {
    id: '17c19242-7bcf-455c-b771-6b2c50371245',
    industry_sector: 'Electrical and Electronics',
    program_title: 'Computer Systems Servicing',
  },
  {
    id: '17c19242-7bcf-455c-b771-6b2c50371246',
    industry_sector: 'Social Community Development',
    program_title: 'Bookkeeping NC III',
  },
];

const subjects = [
  {
    subject_code: 'ME101',
    subject_title: 'Introduction to Metalwork',
    subject_description: 'Overview of metalworking processes and Safety in the workshop',
  },
  {
    subject_code: 'WT102',
    subject_title: 'Basic Welding Theory',
    subject_description: 'Introduction to welding principles and Types of welding processes',
  },
  {
    subject_code: 'SMAW103',
    subject_title: 'Shielded Metal Arc Welding (SMAW) Fundamentals',
    subject_description: 'Basics of SMAW, Equipment and materials',
  },
  {
    subject_code: 'MP104',
    subject_title: 'Metal Properties and Metallurgy',
    subject_description: 'Properties of different metals and Effects of heat on metals',
  },
  {
    subject_code: 'BR105',
    subject_title: 'Blueprint Reading and Welding Symbols',
    subject_description: 'Reading and interpreting blueprints and Understanding welding symbols',
  },
  {
    subject_code: 'PWT106',
    subject_title: 'Practical Welding Techniques I',
    subject_description: 'Basic welding practices and Hands-on training in welding joints',
  },
];

const studentsFromFile = [
  {
    firstName: "ASHLEY DANAYA",
    middleName: "BESAS",
    lastName: "SANICO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-05-06',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "SAM",
    middleName: "MACALOLOT",
    lastName: "HINGPIT",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2002-07-30',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "ELLA",
    middleName: "ALABAT",
    lastName: "ROSILLO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-10-11',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "SHANA RHAYA",
    middleName: "QUILARIO",
    lastName: "GELSANO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2006-08-22',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "CAMERON",
    middleName: "DACERA",
    lastName: "ESPUERTA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "JAMARA",
    middleName: "PAGALAN",
    lastName: "CAGATIN",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "MAYRA GLENN",
    middleName: "LUBAPIS",
    lastName: "HUMAYLAB",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "JEAN KAREN",
    middleName: "SUTANA",
    lastName: "BALBARINO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "RODEL",
    middleName: "JUGAR",
    lastName: "ELANDAG",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "LORDY",
    middleName: "ESPUERTA",
    lastName: "SALOMA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "JANET",
    middleName: "MATURAN",
    lastName: "RUAYA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "KRIZELLE HOPE",
    middleName: "",
    lastName: "DANTES",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "LESTER JOHN",
    middleName: "GAMBING",
    lastName: "MICOMPAL",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "CHIENA",
    middleName: "MASCARDO",
    lastName: "PANGATUNGAN",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "SANDARA",
    middleName: "GENZON",
    lastName: "GALANIDA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "BEIJAY",
    middleName: "PORTA",
    lastName: "BERBAL",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "NOAH",
    middleName: "TAPALES",
    lastName: "JAMEN",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "DHANAYA",
    middleName: "GENZON",
    lastName: "LUBAPIS",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "STEPHANIE",
    middleName: "LUBAPIS",
    lastName: "CONSIGNA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "HORACE MIGUEL",
    middleName: "DACERA",
    lastName: "QUIRIDO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "MARJORY",
    middleName: "CANTA",
    lastName: "TAMAYO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "CRISA",
    middleName: "APORBO",
    lastName: "QUISADA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "JELIAN",
    middleName: "TINAMBACAN",
    lastName: "PANGATUNGAN",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "ENGIELO",
    middleName: "CINCO",
    lastName: "BOHOL",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371246"
  },
  {
    firstName: "ROLDSKIE",
    middleName: "RAGAS",
    lastName: "BESAS",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JOHARY",
    middleName: "ELANDAG",
    lastName: "JACOBE",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JUNE DENVER",
    middleName: "DIZON",
    lastName: "PELIAS",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JURYDINE",
    middleName: "MEDRANO",
    lastName: "GAMUTAN",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JIMUEL",
    middleName: "HINGPIT",
    lastName: "DANELIZ",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "AIVAN",
    middleName: "DELIMAN",
    lastName: "MORIAL",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "DENCH HECLER",
    middleName: "CINCO",
    lastName: "BOHOL",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JELAI",
    middleName: "DARAMAN",
    lastName: "GAZO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "YUHANCE EZEKIEL",
    middleName: "JUANITE",
    lastName: "DOTILLOS",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "NIKO",
    middleName: "ALABAT",
    lastName: "ESPUERTA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JUMIL JHONE",
    middleName: "TARTAR",
    lastName: "JHONE",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JOHN LLOYD",
    middleName: "DIGAL",
    lastName: "ADLAO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JAKITSAN",
    middleName: "BANAYBANAY",
    lastName: "CAWALING",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "DEAN PATRICK",
    middleName: "TARTAR",
    lastName: "PINGOY",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JOEL",
    middleName: "TESADO",
    lastName: "BORDAS",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "OWEN-KIM",
    middleName: "JOAQUINO",
    lastName: "BUYSER",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "LINDA",
    middleName: "BERBAL",
    lastName: "CAPISTRANO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "AQUERA",
    middleName: "RODILA",
    lastName: "RIVAS",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JINKY",
    middleName: "MONTER",
    lastName: "TESADO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "HARVEY KHENJE",
    middleName: "RUDELA",
    lastName: "CUBILLAN",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "JUSTINE IVAN",
    middleName: "MEDRANO",
    lastName: "TARO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "SAM",
    middleName: "GROMACON",
    lastName: "VIRTUDAZO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "CRIAH",
    middleName: "CARDUZA",
    lastName: "CANTA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "LEA SANDARA",
    middleName: "DANO",
    lastName: "BARQUEZ",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "17c19242-7bcf-455c-b771-6b2c50371245"
  },
  {
    firstName: "REYJON",
    middleName: "PLAZA",
    lastName: "RAMIREZ",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "RHEO",
    middleName: "JUANITE",
    lastName: "MATURAN",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JOEHANIE",
    middleName: "DALANGIN",
    lastName: "UBOS",
    suffix: "",
    gender: "MALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "AKEE",
    middleName: "GRUMACON",
    lastName: "MATURAN",
    suffix: "",
    gender: "MALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "PRINCESS KRISTINE",
    middleName: "SARONG",
    lastName: "GELSANO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "RAJIM",
    middleName: "SAGA",
    lastName: "GARRIDO",
    suffix: "",
    gender: "MALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JHON MARK",
    middleName: "LAURON",
    lastName: "VERTICAL",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "SHARI JANE",
    middleName: "PLAZA",
    lastName: "DACERA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "LIZEL",
    middleName: "PLAZA",
    lastName: "DACERA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "CHRISTIAN",
    middleName: "BALBARINO",
    lastName: "GELSANO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "RODRANICK",
    middleName: "DAPAR",
    lastName: "GELSANO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "GELA",
    middleName: "RUDELA",
    lastName: "GELSANO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "LOLITO",
    middleName: "DACERA",
    lastName: "BUO",
    suffix: "",
    gender: "MALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "PIA LUZ",
    middleName: "BANAYBANAY",
    lastName: "BUO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JONEL",
    middleName: "ANGCOG",
    lastName: "LAUGO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "KENETH",
    middleName: "MANTE",
    lastName: "OCON",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "PATRICK",
    middleName: "SARONG",
    lastName: "PLAZA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "SANNY BOY",
    middleName: "CULATA",
    lastName: "HINGPIT",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "ESTANISLAO",
    middleName: "CONSIGNA",
    lastName: "CAWALING",
    suffix: "",
    gender: "MALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JACKIELYN",
    middleName: "RAMOS",
    lastName: "MADREDEJO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JAME RICK",
    middleName: "BALBARINO",
    lastName: "LAMPAD",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JUNSAN NICKTON",
    middleName: "RAMIREZ",
    lastName: "LIBAY",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "DIANARA",
    middleName: "BARONDAY",
    lastName: "DANO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "REYAN",
    middleName: "ESCABAL",
    lastName: "TARTAR",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "CLAIRE MARIE",
    middleName: "CRUIZ",
    lastName: "ESPUERTA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JEAN",
    middleName: "HINGPIT",
    lastName: "GELSANO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "MAYBOY",
    middleName: "PAJA",
    lastName: "SUTANA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "WEGGOL",
    middleName: "BALBARINO",
    lastName: "YAMSON",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JADE KEVIEN",
    middleName: "JACOBE",
    lastName: "TESADO",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "ELIORDO",
    middleName: "TINAMBACAN",
    lastName: "GELSANO",
    suffix: "JR",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "LOVELY",
    middleName: "BUYSER",
    lastName: "LIMATO",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "ALRICH",
    middleName: "CRUIZ",
    lastName: "ELANDAG",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "HARLEY KING",
    middleName: "PIEDAD",
    lastName: "CONSIGNA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "SERMILITO",
    middleName: "ALONG",
    lastName: "SAGA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "GLENA MARIE",
    middleName: "BESAS",
    lastName: "YAMSON",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JEKIM",
    middleName: "CONSIGNA",
    lastName: "MACABODBOD",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "JAMES ERIC",
    middleName: "MONDRAGON",
    lastName: "SILVA",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "TRECIA",
    middleName: "DACERA",
    lastName: "GEDE",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "DONNARIZA",
    middleName: "QUIRIDO",
    lastName: "GEDE",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "ROYICK",
    middleName: "SAVANDAL",
    lastName: "PIEDAD",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "WENDEL",
    middleName: "GONZALES",
    lastName: "GODINEZ",
    suffix: "",
    gender: "MALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "ANALYN",
    middleName: "GELSANO",
    lastName: "CONSIGNA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "ALIJANE",
    middleName: "CANTA",
    lastName: "BORDAS",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "SINGLE",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  },
  {
    firstName: "SHARA",
    middleName: "DANO",
    lastName: "CALAMBA",
    suffix: "",
    gender: "FEMALE",
    civilStatus: "MARRIED",
    birthday: '2005-12-23',
    birthPlace: "",
    nationality: "",
    religion: "",
    ethnicity: "",
    facebook: "",
    skype: "",
    zoom: "",
    courseId: "64ffa120-aa8a-4ab1-9396-4100342fb0f5"
  }
];

module.exports = {
  users,
  students,
  courses,
  subjects,
  studentsFromFile,
};
